# Generated by Django 3.0.8 on 2020-07-26 20:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_listing_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='highest_bid_owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_highest_bid_listings_set', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
