# Generated by Django 3.0.8 on 2020-07-26 23:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_listing_highest_bid_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='winner',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_wins_set', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
